### ISSUE TITLE
Vehicle Updating : Garage

### ISSUE THREAD

**Issue by Yumshot** [OfficialDarkzy/DRP-ID#3]
As stated in discord , Vehicle states are not updating.

> **Recreate** : Buy a car , leave server , restart server , remove vehicle from garage , exit vehicle, check garage, vehicle state will still be in even though vehicle is pulled out next to you.

Will PR when I have figured it out.

**Comment by OfficialDarkzy** [comment]
Cheers, I can have a look into it too. Needs a remover or something when people leave etc... but can be personal reference

**Comment by Yumshot** [comment]
Things I've discovered that may be helpful.
StateChangeIn is referenced server sided but never used.
StateChangeOut is returning the network id while the spawnVehicle function is being called but in StateChangeOut its using the networkid from the client call instead of plate?


> **FIX** : `RegisterServerEvent("DRP_Garages:StateChangeOut")
AddEventHandler("DRP_Garages:StateChangeOut", function(plate)
	local src = source
	TriggerEvent("DRP_ID:GetCharacterData", src, function(CharacterData)
		exports["externalsql"]:DBAsyncQuery({
            string = "UPDATE vehicles SET `state` = :state WHERE `plate` = :plate",
            data = {
                plate = plate,
                state = "OUT"
            }
        }, function(results)
		end)
	end)
end)`

The function was first calling id , yet id was returning a networkID , which has no reference in database. However plate does.
