### ISSUE TITLE
Character creation

### ISSUE THREAD

**Issue by Yumshot** [OfficialDarkzy/DRP-ID#5]
Not sure if you had your own UI or something , but character creation never pops after creating a character , you're just spawned as a default. 
I'll create a trigger to open the clothing store UI on first spawn if you don't have anything planned

**Comment by OfficialDarkzy** [comment]
Yeha did that on purpose... I personally wanted to add the option for server owners to have it open character editing when they load in or they spawn with default gear and make them have to run to a clothing store.

**Comment by Yumshot** [comment]
Ultimately all choice one needs is a way of registering is this first spawn after creating character , then triggering event for shop menu.
I'll write an if statement to check for a true config setting and write something up as a "give server owners" choice path if you want me to PR it when I'm done I will as it's not really a necessity.

**Comment by OfficialDarkzy** [comment]
yeah that would be good please, just a basic if statement and it will require a config variable also

**Comment by Yumshot** [comment]
Working on this today , hopefully will close by the end of day

**Comment by OfficialDarkzy** [comment]
No updates, will put this on a list of things to do/ get clothing better
